export {default  as About} from './About/About';
export {default  as Cart } from './Cart/Cart';
export {default  as Checkout} from './Checkout/Checkout';
export {default  as Error} from './Error/Error';
export {default  as Home} from './Home/Home';
export {default  as Login} from './Login/Login';
export {default  as Orders} from './Orders/Orders';
export {default  as Products} from './Products/Products';
export {default  as Register} from './Register/Register';
export {default  as SingleProduct} from './SingleProduct/SingleProduct';
export {default as MainLayout } from './MainLayout';
export {default as Header } from '../components/Header';
export {default as NavBar} from '../components/NavBar';
export {default as SinglePageError} from './Error/SinglePageError';
export {default as SectionTitle} from '../common/SectionTitle';