export const ACTION_TYPES__CART_ENUM = {
    REMOVE_ELEMENT:"REMOVE_ELEMENT",
    CLEAR:"CLEAR_CART",
    UPDATE_AMOUNT:"UPDATE_AMOUNT",
    SET_CART_VALUE:"SET_CART_VALUE",
    SET_LOADING:"SET_LOADING"
}
