export const countriesMinName = [
    { country:"Argentina",min:"AR"},
    { country:"Bolivia",min:"BL"},
    { country:"Brazil",min:"BR"},
    { country:"Canada",min:"CA"},
    { country:"Chile",min:"CL"},
    { country:"Colombia",min:"CO"},
    { country:"Costa Rica",min:"CR"},
    { country:"Ecuador",min:"EC"},
    { country:"Estados Unidos",min:"US"},
    { country:"Jamaica",min:"JM"},
    { country:"México",min:"MX"},
    { country:"Panamá",min:"PA"},
    { country:"Paraguay",min:"PY"},
    { country:"Perú",min:"PE"},
    { country:"Uruguay",min:"UY"},
    { country:"Venezuela",min:"VE"},
]